module.exports = [
    { Year: 1395, Day:   1, OffDay: true  , Description: 'جشن نوروز'},
    { Year: 1395, Day:   6, OffDay: false , Description: 'روز امید / روز شادباش‌نویسی'},
    { Year: 1395, Day:  10, OffDay: false , Description: 'جشن آبان‌گاه'},
    { Year: 1395, Day:  13, OffDay: false , Description: 'جشن سیزده‌به‌در'},
    { Year: 1395, Day:  17, OffDay: false , Description: 'سروش روز، جشن سروش‌گان'},
    { Year: 1395, Day:  19, OffDay: false , Description: 'فروردین روز، جشن فروردین‌گان'},
    { Year: 1395, Day:  33, OffDay: false , Description: 'جشن گیاه‌آوری'},
    { Year: 1395, Day:  34, OffDay: false , Description: 'اردیبهشت روز، جشن اردیبهشت‌گان'},
    { Year: 1395, Day:  41, OffDay: false , Description: 'جشن چهلم نوروز'},
    { Year: 1395, Day:  46, OffDay: false , Description: 'گاهنبار میدیوزَرِم، جشن میانه بهار، جشن بهاربد / روز پیام‌آوری زرتشت'},
    { Year: 1395, Day:  63, OffDay: false , Description: 'ارغاسوان، جشن گرما'},
    { Year: 1395, Day:  68, OffDay: false , Description: 'خرداد روز، جشن خردادگان'},
    { Year: 1395, Day:  94, OffDay: false , Description: 'جشن آب‌پاشونک، جشن آغاز تابستان / سال نو در گاهشماری گاهنباری'},
    { Year: 1395, Day:  99, OffDay: false , Description: 'جشن نیلوفر'},
    { Year: 1395, Day: 106, OffDay: false , Description: 'تیرروز، جشن تیرگان'},
    { Year: 1395, Day: 108, OffDay: false , Description: 'جشن خام‌خواری'},
    { Year: 1395, Day: 131, OffDay: false , Description: 'مردادروز، جشن مردادگان'},
    { Year: 1395, Day: 134, OffDay: false , Description: 'جشن چهلم تابستان'},
    { Year: 1395, Day: 139, OffDay: false , Description: 'گاهنبار میدیوشِم، جشن میانه تابستان'},
    { Year: 1395, Day: 142, OffDay: false , Description: 'جشن مَی‌خواره'},
    { Year: 1395, Day: 156, OffDay: false , Description: 'فغدیه، جشن خنکی هوا'},
    { Year: 1395, Day: 158, OffDay: false , Description: 'جشن کشمین'},
    { Year: 1395, Day: 159, OffDay: false , Description: 'شهریورروز، جشن شهریورگان / زادروز داراب (کوروش) / عروج مانی'},
    { Year: 1395, Day: 163, OffDay: false , Description: 'خزان جشن'},
    { Year: 1395, Day: 170, OffDay: false , Description: 'بازار جشن'},
    { Year: 1395, Day: 186, OffDay: false , Description: 'گاهنبار پَتیَه‌شَهیم، جشن پایان تابستان'},
    { Year: 1395, Day: 187, OffDay: false , Description: 'جشن میتراکانا / سال نو هخامنشی'},
    { Year: 1395, Day: 195, OffDay: false , Description: 'آیین قالیشویان اردهال، بازماندی از تیرگان'},
    { Year: 1395, Day: 199, OffDay: false , Description: 'تیرروز، جشن تیرروزی'},
    { Year: 1395, Day: 202, OffDay: false , Description: 'مهرروز، جشن مهرگان'},
    { Year: 1395, Day: 207, OffDay: false , Description: 'رام روز، جشن رام روزی / جشن پیروزی کاوه و فریدون'},
    { Year: 1395, Day: 226, OffDay: false , Description: 'آبان روز، جشن آبان‌گان'},
    { Year: 1395, Day: 231, OffDay: false , Description: 'گاهنبار اَیاثرَم، جشن میانه پاییز'},
    { Year: 1395, Day: 247, OffDay: false , Description: 'آذر جشن'},
    { Year: 1395, Day: 255, OffDay: false , Description: 'آذر روز، جشن آذرگان'},
    { Year: 1395, Day: 276, OffDay: false , Description: 'جشن شب یلدا (چله) / گاهنبار میدیارِم، جشن میانه سال گاهنباری و پایان پاییز'},
    { Year: 1395, Day: 277, OffDay: false , Description: 'روز میلاد خورشید، جشن خرم روز / نخستین جشن دی‌گان'},
    { Year: 1395, Day: 281, OffDay: false , Description: 'بازار جشن'},
    { Year: 1395, Day: 284, OffDay: false , Description: 'دی به آذر روز، دومین جشن دی‌گان'},
    { Year: 1395, Day: 290, OffDay: false , Description: 'سیر روز، جشن گیاه‌خواری'},
    { Year: 1395, Day: 291, OffDay: false , Description: 'جشن پیکرتراشی / دی به مهر روز، سومین جشن دی‌گان'},
    { Year: 1395, Day: 292, OffDay: false , Description: 'جشن درامزینان، جشن درفش‌ها'},
    { Year: 1395, Day: 299, OffDay: false , Description: 'دی به دین روز، چهارمین جشن دی‌گان'},
    { Year: 1395, Day: 307, OffDay: false , Description: 'زادروز فردوسی'},
    { Year: 1395, Day: 308, OffDay: false , Description: 'بهمن روز، جشن بهمن‌گان'},
    { Year: 1395, Day: 310, OffDay: false , Description: 'شهریور روز، آغاز پادشاهی داراب (کوروش)'},
    { Year: 1395, Day: 311, OffDay: false , Description: 'جشن نوسَره'},
    { Year: 1395, Day: 316, OffDay: false , Description: 'آبان روز، جشن سَدَه، آتش افروزی بر بام‌ها / نمایش بازی همگانی'},
    { Year: 1395, Day: 321, OffDay: false , Description: 'جشن میانه زمستان'},
    { Year: 1395, Day: 328, OffDay: false , Description: 'بادروز، جشن بادروزی'},
    { Year: 1395, Day: 337, OffDay: false , Description: 'جشن اسفندی / جشن آبسالان، بهار جشن / نمایش بازی همگانی'},
    { Year: 1395, Day: 341, OffDay: false , Description: 'اسفند روز، جشن اسفندگان، گرامی‌داشت زمین و بانوان / جشن برزگران'},
    { Year: 1395, Day: 346, OffDay: false , Description: 'جشن وخشنکام'},
    { Year: 1395, Day: 355, OffDay: false , Description: 'جشن نوروز رودها'},
    { Year: 1395, Day: 356, OffDay: false , Description: 'جشن گلدان'},
    { Year: 1395, Day: 361, OffDay: false , Description: 'پایان سرایش شاهنامه فردوسی'},
    { Year: 1395, Day: 362, OffDay: false , Description: 'فروردگان'},
    { Year: 1395, Day: 365, OffDay: false , Description: 'گاهنبار هَمَسپَتمَدَم، جشن پایان زمستان / زادروز زرتشت / جشن اوشیدر (نجات بخش ایرانی) در دریاچه هامون و کوه خواجه / آتش افروزی بر بام‌ها در استقبال از نوروز'}
]